# This file is based on
# https://github.com/Ifsttar/I-Simpa/blob/master/appveyor.yml

# specify custom environment variables
environment:
  matrix:
    - VisualStudioVersion: 14.0
      platform: x64
      configuration: Release
    - VisualStudioVersion: 14.0
      platform: x86
      configuration: Release
  global:
    MSVC_DEFAULT_OPTIONS: ON
    WXWIN: C:\wxWidgets-3.1.1\
    wxWidgets_ROOT_DIR: C:\wxWidgets-3.1.1\
    wxWidgets_INCLUDE_DIRS: C:\wxWidgets-3.1.1\include
    wxWidgets_LIBRARIES: C:\wxWidgets-3.1.1\lib\vc140_x64_dll


# clone directory
clone_folder: c:\projects\wxMaxima

# Operating system (build VM template)
# os: Visual Studio 2015

#platform: x64
#configuration: Release


# scripts to run before build
before_build:
  - set WXWIN=C:\wxWidgets-3.1.1\
  - set wxWidgets_ROOT_DIR=%WXWIN%
  - set wxWidgets_LIB_DIR=%WXWIN%\lib\vc_dll
  - ps: Start-FileDownload 'https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.1/wxWidgets-3.1.1.7z'
  - ps: Start-FileDownload 'https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.1/wxMSW-3.1.1_vc140_x64_Dev.7z'
  - cmd: 7z x wxWidgets-3.1.1.7z -oC:\wxWidgets-3.1.1
  - cmd: 7z x wxMSW-3.1.1_vc140_x64_Dev.7z -oC:\wxWidgets-3.1.1
  - cmd: dir %wxWidgets_LIBRARIES%
  - ps: Start-FileDownload 'https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.1/wxMSW-3.1.1_vc140_x64_ReleaseDLL.7z' -Timeout 15000
  - cmd: 7z x wxMSW-3.1.1_vc140_x64_ReleaseDLL.7z -oC:\wxWidgets-3.1.1
  - echo Running cmake...
  - cmd: mkdir c:\projects\wxMaxima\build
  - cmd: cd c:\projects\wxMaxima\build
  - cmd: echo wxWidgets_CONFIGURATION:STRING=mswu > CMakeCache.txt
  - cmd: echo wxWidgets_LIB_DIR:PATH=%wxWidgets_LIBRARIES% >> CMakeCache.txt
  - cmd: echo wxWidgets_ROOT_DIR:PATH=%wxWidgets_ROOT_DIR% >> CMakeCache.txt
  - cmd: echo WX_LIB_DIR:INTERNAL=%wxWidgets_LIBRARIES% >> CMakeCache.txt
  - cmd: echo WX_ROOT_DIR:INTERNAL=%wxWidgets_ROOT_DIR% >> CMakeCache.txt
  - cmake -D CMAKE_CXX_FLAGS="/MTd /EHsc" c:\projects\wxMaxima 

build_script:
  - cd c:\projects\wxMaxima\build
  - 'CALL "C:\Program Files (x86)\Microsoft Visual Studio %VisualStudioVersion%\VC\vcvarsall.bat"
  - msbuild "INSTALL.vcxproj" /consoleloggerparameters:Verbosity=minimal /target:Build  /p:Configuration=%configuration% /p:Platform=%platform% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
  - cd c:\projects\wxMaxima\build
  - 'CALL "C:\Program Files (x86)\Microsoft Visual Studio %VisualStudioVersion%\VC\vcvarsall.bat"
  - msbuild "PACKAGE.vcxproj" /consoleloggerparameters:Verbosity=minimal /target:Build  /p:Configuration=%configuration% /p:Platform=%platform% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

artifacts:
  - path: 'build\CMakeFiles\CMakeOutput.log'
    name: cmake_output_log
  - path: 'build\*.tar.gz'
    name: tarball
  - path: '\build\src\Release\wxmaxima.exe'
    name: wxMaxima
