# This file is based on
# https://github.com/Ifsttar/I-Simpa/blob/master/appveyor.yml

image:
 - Visual Studio 2017


# clone directory
clone_folder: c:\projects\wxMaxima


# cache the build results in order to speed up the build
cache:
  - build\CMakeFiles

# branches to build
branches:
  only:
    - master

# scripts to run before build
before_build:
  # sent environment variables for wxWidgets
  - cmd: set WXWIN=C:/wxWidgets
  - cmd: set wxWidgets_ROOT_DIR=%WXWIN%
  - ps: Start-FileDownload 'https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.2/wxMSW-3.1.2_vc141_x64_Dev.7z'
  - ps: Start-FileDownload 'https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.2/wxWidgets-3.1.2-headers.7z'
  - cmd: 7z x wxMSW-3.1.2_vc141_x64_Dev.7z -oC:\wxWidgets
  - cmd: 7z x wxWidgets-3.1.2-headers.7z -oC:\wxWidgets
  - cmd: echo Running cmake...
  - cmd: if not exist c:\projects\wxMaxima\build mkdir c:\projects\wxMaxima\build
  - cmd: cd c:\projects\wxMaxima\build
  - cmd: cmake  -LAH -G "Visual Studio 15 2017 Win64" -DAPPVEYOR_BUILD=1 -DCMAKE_BUILD_TYPE=Debug ..

build_script:
  - cmd: cd c:\projects\wxMaxima\build
  - cmd: cmake --build .

after_build:
  - cmd: cd c:\projects\wxMaxima\build
  - cmd: cmake --build . -- package

on_failure:
  - cmd: 7z a FailureDump.zip *
  - cmd: appveyor PushArtifact FailureDump.zip

artifacts:
  - path: 'build/wxmaxima-*.exe'
    name: wxMaxima_Installer
