# This file is based on
# https://github.com/Ifsttar/I-Simpa/blob/master/appveyor.yml

image:
 - Visual Studio 2017


# clone directory
clone_folder: c:\projects\wxMaxima


# cache the build results in order to speed up the build
cache:
  - build\CMakeFiles

# branches to build
branches:
  only:
    - master

# scripts to run before build
before_build:
  # sent environment variables for wxWidgets
  - set WXWIN=C:\wxWidgets
  - set wxWidgets_ROOT_DIR=%WXWIN%
  - set wxWidgets_LIB_DIR=%WXWIN%\lib\vc_dll
  - ps: Start-FileDownload 'https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.2/wxMSW-3.1.2_vc141_x64_Dev.7z'
  - ps: Start-FileDownload 'https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.2/wxMSW-3.1.2_vc141_ReleaseDLL.7z'
  - ps: Start-FileDownload 'https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.2/wxWidgets-3.1.2-headers.7z'
  - ps: Start-FileDownload 'https://github.com/Kitware/CMake/releases/download/v3.14.6/cmake-3.14.6-win64-x64.zip'
  - cmd: 7z x wxMSW-3.1.2_vc141_x64_Dev.7z -oC:\wxWidgets
  - cmd: 7z x wxMSW-3.1.2_vc141_ReleaseDLL.7z -oC:\wxWidgets
  - cmd: 7z x wxWidgets-3.1.2-headers.7z -oC:\wxWidgets
  - cmd: 7z x cmake-3.14.6-win64-x64.zip -oC:\
  - echo Running cmake...
  - cmd: mkdir c:\projects\wxMaxima\build
  - cmd: cd c:\projects\wxMaxima\build
  - cmd: echo wxWidgets_CONFIGURATION:STRING=mswu > CMakeCache.txt
  - cmd: echo wxWidgets_LIB_DIR:PATH=%wxWidgets_LIBRARIES% >> CMakeCache.txt
  - cmd: echo wxWidgets_ROOT_DIR:PATH=%wxWidgets_ROOT_DIR% >> CMakeCache.txt
  - cmd: echo WX_LIB_DIR:INTERNAL=%wxWidgets_LIBRARIES% >> CMakeCache.txt
  - cmd: echo WX_ROOT_DIR:INTERNAL=%wxWidgets_ROOT_DIR% >> CMakeCache.txt
  - C:\cmake-3.14.6-win64-x64\bin\cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON ..

build_script:
  - cd c:\projects\wxMaxima\build
  - CALL "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - msbuild "INSTALL.vcxproj" /consoleloggerparameters:Verbosity=minimal /target:Build /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
  - cd c:\projects\wxMaxima\build
  - CALL "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - msbuild "PACKAGE.vcxproj" /consoleloggerparameters:Verbosity=minimal /target:Build /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

artifacts:
  - path: 'build\CMakeFiles\CMakeOutput.log'
    name: cmake_output_log
  - path: 'build\*.tar.gz'
    name: tarball
  - path: '\build\src\Release\wxmaxima.exe'
    name: wxMaxima
