# This file is based on
# https://github.com/Ifsttar/I-Simpa/blob/master/appveyor.yml

# specify custom environment variables
environment:
  matrix:
    - VisualStudioVersion: 14.0
      platform: x64
      configuration: Release
      vcvarsall_platform: "x64"
  global:
    MSVC_DEFAULT_OPTIONS: ON

# clone directory
clone_folder: c:\projects\wxMaxima

# cache the build results in order to speed up the build
#cache:
#  - build\CMakeFiles

# branches to build
branches:
  # whitelist
  only:
    - master

# Operating system (build VM template)
os: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:

platform: x64
configuration: Release


# scripts to run before build
before_build:
  - ps: Start-FileDownload 'https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.0/wxWidgets-3.1.0.7z'
  - ps: Start-FileDownload 'https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.0/wxMSW-3.1.0_vc140_x64_Dev.7z'
  - ps: Start-FileDownload 'https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.0/wxMSW-3.1.0_vc140_x64_ReleaseDLL.7z' -Timeout 15000
  - cmd: 7z x wxWidgets-3.1.0.7z -oC:\wxWidgets
  - cmd: 7z x wxMSW-3.1.0_vc140_x64_Dev.7z -oC:\wxWidgets
  - cmd: 7z x wxMSW-3.1.0_vc140_x64_ReleaseDLL.7z -oC:\wxWidgets
  - echo Running cmake...
  - cmd: mkdir c:\projects\wxMaxima\build
  - cmd: cd c:\projects\wxMaxima\build
  - cmake -G "Visual Studio 14 2015 Win64" c:\projects\wxMaxima -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON .. -DwxWidgets_ROOT_DIR="C:\wxWidgets\" -DwxWidgets_LIBRARIES="C:\wxWidgets\lib\vc140_x64_dll"

build_script:
  - cd c:\projects\wxMaxima\build
  - 'CALL "C:\Program Files (x86)\Microsoft Visual Studio %VisualStudioVersion%\VC\vcvarsall.bat" %vcvarsall_platform%'
  - msbuild "INSTALL.vcxproj" /consoleloggerparameters:Verbosity=minimal /target:Build  /p:Configuration=%configuration% /p:Platform=%platform% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
  - cd c:\projects\wxMaxima\build
  - 'CALL "C:\Program Files (x86)\Microsoft Visual Studio %VisualStudioVersion%\VC\vcvarsall.bat" %vcvarsall_platform%'
  - msbuild "PACKAGE.vcxproj" /consoleloggerparameters:Verbosity=minimal /target:Build  /p:Configuration=%configuration% /p:Platform=%platform% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

artifacts:
  - path: 'build\CMakeFiles\CMakeOutput.log'
    name: cmake_output_log
  - path: 'build\*.tar.gz'
    name: tarball
  - path: '\build\src\Release\wxmaxima.exe'
    name: wxMaxima
