# This file is based on
# https://github.com/Ifsttar/I-Simpa/blob/master/appveyor.yml

image:
 - Visual Studio 2017

# clone directory
clone_folder: c:\projects\wxMaxima


# cache the build results in order to speed up the build
cache:
  - C:\wxwidgets-install_3.1.2
  - c:\projects\wxMaxima\build\CMakeCache.txt
  - c:\projects\wxMaxima\build\CMakeFiles
  - c:\projects\wxMaxima\build\src\CMakeFiles
  - c:\projects\wxMaxima\build\src\Release
  - C:\ProgramData\chocolatey\bin
  - C:\ProgramData\chocolatey\lib
  
# branches to build
branches:
  only:
    - master

# scripts to run before build
before_build:
  - cmd: echo Installing maxima...
  - cmd: choco install maxima
  - cmd: echo Downloading and unpacking wxWidgets...
  - cmd: set WXVERSION=3.1.2
  - ps: Start-FileDownload 'https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.2/wxWidgets-3.1.2.7z'
  - cmd: echo "compiling wxwidgets from source"
  - cmd: if not exist C:\wxwidgets-install_%WXVERSION% 7z x wxWidgets-%WXVERSION%.7z -oC:\wxwidgets-source_%WXVERSION%
  - cmd: if not exist C:\wxwidgets-build_%WXVERSION% mkdir C:\wxwidgets-build_%WXVERSION%
  - cmd: cd C:\wxwidgets-build_%WXVERSION%
  - cmd: CALL "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cmd: if not exist C:\wxwidgets-install_%WXVERSION% cmake -AH -G "Visual Studio 15 2017 Win64" -DwxBUILD_SHARED=NO --config Release -DCMAKE_INSTALL_PREFIX=C:\wxwidgets-install_%WXVERSION% ../wxwidgets-source_%WXVERSION% -DCMAKE_STATIC_LINKER_FLAGS="/INCREMENTAL" -DCMAKE_MODULE_LINKER_FLAGS="/INCREMENTAL"
  - cmd: if not exist C:\wxwidgets-install_%WXVERSION% cmake --build . --config Release
  - cmd: if not exist C:\wxwidgets-install_%WXVERSION% cmake --build . --config Release --target install
  - cmd: echo Running cmake...
  - cmd: if not exist c:\projects\wxMaxima\build mkdir c:\projects\wxMaxima\build
  - cmd: cd c:\projects\wxMaxima\build
  - cmd: cmake  -AH -G "Visual Studio 15 2017 Win64" -DAPPVEYOR_BUILD=1 --config Release -DwxWidgets_ROOT_DIR=C:\wxwidgets-install_%WXVERSION% -D CMAKE_CXX_FLAGS="/EHsc /D_UNICODE=1" -DwxWidgets_CONFIGURATION=mswu ..

build_script:
  - cmd: cd c:\projects\wxMaxima\build
  - cmd: cmake --build . --config Release
  - cmd: ctest

after_build:
  - cmd: cd c:\projects\wxMaxima\build
  - cmd: CALL "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - cpack -G NSIS

on_failure:
  - cmd: 7z a FailureDump.zip *
  - cmd: appveyor PushArtifact FailureDump.zip

artifacts:
  - path: 'build/wxmaxima-*.exe'
    name: wxMaxima_Installer
