language: cpp
sudo: required
os:
- linux
- osx
branches:
  except:
  - gh_pages
  - DebianPackaging
dist: bionic
cache:
  ccache: true
  directories:
  - "$HOME/Library/Caches/Homebrew"
  - /usr/local/Cellar/libpng
  - /usr/local/Cellar/gettext
  - /usr/local/Cellar/ccache
addons:
  ssh_known_hosts: home67027059.1and1-data.host
  apt:
    packages:
    - libwxgtk3.0-gtk3-dev
    - libwxgtk3.0
    - gettext
    - doxygen
    - graphviz
    - rpm
    - cmake
    - maxima
    - netcat-openbsd
    - xvfb
    - appstream-util
    - desktop-file-utils
    - pandoc
    - po4a
    - texlive-latex-base
    - texlive-latex-extra
    - lmodern
    - texlive-fonts-recommended
before_cache:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cleanup; fi
before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
     export HOMEBREW_LOGS;brew update
     export PATH="/usr/local/opt/ccache/libexec:$PATH"
     brew install ccache
     brew link ccache
     export PATH=/usr/local/opt/texinfo/bin:$PATH:/usr/local/opt/gettext/bin
     brew install gettext texinfo wxwidgets pandoc homebrew/cask/basictex
  fi
notification:
  email:
    on_success: change
    on_failure: change
git:
  depth: 15
script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CXXFLAGS="-Wall -Wextra -fcolor-diagnostics";
  else export CXXFLAGS="-Wall -Wextra -ansi -std=c++11"; fi
- mkdir build && cd build && cmake .. && cmake --build .
- cmake --build . -- install DESTDIR=$(pwd)/installtest
- cmake --build . -- package
- mkdir -p deploy
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cp *.dmg deploy/wxMaxima-nightly.dmg; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then CTEST_OUTPUT_ON_FAILURE=1 xvfb-run -a make test ; fi
- cd ..
- ccache -s
- ls build/deploy
- mkdir -p .ssh
- openssl aes-256-cbc -K $encrypted_f94fa95f949a_key -iv $encrypted_f94fa95f949a_iv -in .travis/deploy_rsa.enc -out .ssh/id_rsa -d
- chmod 600 .ssh/id_rsa
- eval "$(ssh-agent -s)"
- ssh-add .ssh/id_rsa
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo "put deploy/wxMaxima-nightly.dmg" | sftp -i .ssh/id_rsa p33761049-travis@home67027059.1and1-data.host; fi

env:
  global:
    secure: FOIPVgpFCQjLbFI+mOmCTu4MLh7jqgV2bwKOr3zfcJzFTV+0pHP42GWJfS1Krf5MTrztYx+2p38ovK1Gq09HCBCR7Qc9C7brM961Nvqt2tFlFXXEfrE73unUHU/CxJlCi+1O9oQQJby7X+/IaZr5nDmbkKCjSBiEsajiI5Jtb+Xiopr9cJfT4cDZwofdPo7RME8/zzMao9gtPgk9fkeeQWg9JhECQ4zLdxyaJb1osx8oZ/wd6fOvhW2E5zMczv/svb3hR9dYSPF2K547+JZMaQtbA17MZ4xd59FR8JISnfwtiAihU1ngtm6l9/H6EkuoP4ndhBR9aMMLOfUxiH1UKUsFmazhqhwvWDEuScD60dXV/ulyCaLw1kVunWQd6rkmx12OU22omqP61+9Cg6OIib8BuW4w72O9WqoYVNf6ZrjTX3q9axSPlAzliMvivmUB8UsYEKTmNrWi+a0mStyGbFPMi4TwFgmbCp3SnNOq4Qe7XsjcBAQJ4BlgzMAQdaMBm2gLdGVxaVwSbhTD7W7f/2PKg/A/OvT8QEdj4jwq3qaV4b1MMLwoTRmKVZPFGaaU2HLumrM8uqeJVkOPXBV+2lx8BYCQqfbAwrgOkuNNEAjNqut87/06husmdlPKjVOVBGXQnHF5u0aD5k0oMtgfeoKPw93cvQn/6XMFtJqiPFM=
