language: cpp
sudo: required

os:
  - linux
  - osx

osx_image: xcode8.2

branches:
  only:
    - master

cache: ccache

before_install: 
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update                                             ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libwxgtk3.0-dev libwxgtk3.0  gettext ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update                                  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install wxwidgets gettext texinfo       ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=$PATH:/usr/local/opt/gettext/bin ; fi

notification:
  email:
    recipients:
      - andrej.vodopivec@gmail.com
    on_success: change
    on_failure: change

git:
  depth: 15

script: |
  cp .travis/wxwin.m4 acinclude.m4 &
  ./bootstrap &&
  ./configure --enable-static-wx --enable-fullystatic&&
  make &&
  make dist &&
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make wxMaxima.app ; fi
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then tar cvzf wxMaxima_nightly.app.zip wxMaxima.app ; fi
