language: cpp
sudo: required

os:
  - linux
  - osx

branches:
  only:
    - master

before_install: 
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update                                             ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libwxgtk3.0-dev libwxgtk3.0 texinfo gettext ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update                            ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install wxwidgets gettext texinfo ; fi

notification:
  email:
    recipients:
      - andrej.vodopivec@gmail.com
    on_success: change
    on_failure: change

git:
  depth: 3

script: |
  curl https://raw.githubusercontent.com/wxWidgets/wxWidgets/master/wxwin.m4 -o acinclude.m4 &&
  ./bootstrap &&
  ./configure &&
  make &&
  make dist
