language: cpp
sudo: required

os:
  - linux
  - osx

osx_image: xcode8.2

branches:
  only:
    - master

cache: ccache

before_install: 
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update                                             ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libwxgtk3.0-dev libwxgtk3.0  gettext ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update                                  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install --with-static wxwidgets         ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gettext texinfo                 ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH=$PATH:/usr/local/opt/gettext/bin ; fi

notification:
  email:
    recipients:
      - andrej.vodopivec@gmail.com
    on_success: change
    on_failure: change

git:
  depth: 15

script: |
  cp .travis/wxwin.m4 acinclude.m4 &
  ./bootstrap &&
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./configure --with-macosx-version-min=10.9 --enable-static-wx --enable-fullystatic;else ./configure --enable-static-wx --enable-fullystatic;fi&&
  make &&
  make dist &&
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then make wxMaxima.app ; fi &&
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then tar cvzf wxMaxima_nightly.app.zip wxMaxima.app ; fi &&
  openssl aes-256-cbc -K $encrypted_f94fa95f949a_key -iv $encrypted_f94fa95f949a_iv -in data/wxMaxima.key.enc -out data/wxMaxima.key -d &&
  chmod 600 data/wxMaxima.key &&
  eval `ssh-agent -s` &&
  ssh-add data/wxMaxima.key &&
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo "put wxMaxima_nightly.app.zip" |sftp -i wxMaxima/wxMaxima.key -o StrictHostKeyChecking=no p33761049-wxMaxima@p33761049.1and1-data.host: ; fi

