language: cpp
sudo: required

branches:
  only:
    - master

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libwxgtk3.0-dev libwxgtk3.0

notification:
  email:
    recipients:
      - andrej.vodopivec@gmail.com
    on_success: change
    on_failure: change

git:
  depth: 3

script: |
  curl https://raw.githubusercontent.com/wxWidgets/wxWidgets/master/wxwin.m4 -o aclocal.m4 &&
  ./bootstrap &&
  ./configure &&
  make &&
  make dist
