install:
  - set "PATH=C:\msys64\usr\bin;C:\msys64\mingw64\bin;%PATH%"
  - set MSYSTEM=MINGW64
  - pacman -Sy --noconfirm pacman-mirrors
  - pacman -S --noconfirm pacman
  - pacman --sync --noconfirm base-devel
  - pacman --sync --noconfirm msys2-devel
  - pacman --sync --noconfirm mingw-w64-x86_64-toolchain
  - pacman --sync --noconfirm mingw-w64-x86_64-wxWidgets
  

build_script:
  - ps: >-
      bash -c @"
       cp .travis/wxwin.m4 acinclude.m4
       ./bootstrap
       ./configure
       make
      "@
