name: wxMaxima
version: 16.10~git
summary: A nightly build of wxMaxima, a gui for Maxima, a full-featured CAS.
description: wxMaxima is a quite full-featured graphical user interface for maxima..

apps:
  wxMaxima:
    command: wxmaxima
