name: wxmaxima
version: 16.10~git
summary: A nightly build of wxMaxima, a gui for Maxima, a full-featured CAS.
description: wxMaxima is a quite full-featured graphical user interface for maxima.
confinement: strict
grade: devel

apps:
  wxmaxima:
    command: wxmaxima
    desktop: usr/share/applications/wxMaxima.desktop
    plugs:
     - network
     - home
     - removable-media
     - optical-drive
     - process-control

parts:
  wxmaxima:
    plugin: autotools
    source: .
    build-packages:
     - libwxbase3.0-dev
     - libwxgtk3.0-dev
     - gettext
    stage-packages:
     - maxima
     - maxima-doc
